module MeedNotificationType
  JOB_POSTING = 'job_posting'
  JOB_INVITATION = 'job_invitation'
  JOB_SHORTLIST = 'job_shortlist'
  APPLICATION_OPEN = 'application_open'
  MESSAGE_RECEIVED = 'message_received'
  FOLLOW_COLLECTION = 'follow_collection'
  UPVOTE_COURSE_REVIEW = 'upvote_course_review'
  UPVOTE_PROFILE_UPDATE = 'upvote_profile_update'
  UPVOTE_STORY = 'upvote_story'
  UPVOTE_PROFILE_ENDORSEMENT = 'upvote_profile_endorsement'
  COMMENT_STORY = 'comment_story'
  FRIEND_JOINED = 'friend_joined'
  THREADED_COMMENT_STORY = 'threaded_comment_story'
  QUESTION_ASK = 'question_ask'
  UPVOTE_ANSWER = 'upvote_answer'
  FOLLOW_USER = 'follow_user'
  UPVOTE_COMMENT = 'upvote_comment'
end