module UserFeedTypes
  COURSEWORK = 'coursework'
  EDUCATION = 'education'
  INTERNSHIP = 'internship'
  JOB = 'job'
  OBJECTIVE = 'objective'
  PROFILE_PICTURE = 'profile_picture'
  FOLLOW_COLLECTION = 'follow_collection'
  PUBLICATION = 'publication'
  QUESTION = 'question'
  REQUIREMENT = 'requirement'
  SKILLS = 'skills'
  STORY = 'story'
  EVENT = 'event'
  USERWORK = 'userwork'
  USER_COURSE_REVIEW = 'user_course_review'
  USER_COURSE_REFERENCE = 'user_course_reference'
  USER_WORK_REFERENCE = 'user_work_reference'
end