module REDIS_KEYS
  key = 6
  CACHE_WEEKLY_TOP_FEED = "feed-items-weekly-#{key}"
  CACHE_COLLECTION_FEED_PTFLO = "collection-feed-user-portfolio-#{key}"
  CACHE_COLLECTION_RECOMMENDATIONS = "collection-recommendations-#{key}"
  CACHE_INFLUENCER_RECOMMENDATION_IDS = "collection-influencer-recommendations-#{key}"
  CACHE_COLLECTION_FEED= "collection-feed-#{key}"
  CACHE_TAG_FEED= "tag-feed-#{key}"
  CACHE_MAJOR_DEGREES = "majors-degrees-#{key}"
  CACHE_OAUTH_TOKEN = "majors-degrees-#{key}"
  CACHE_NOTIFICATIONS = "notifications-#{key}"
  CACHE_NOTIFICATION_COUNT = "notification-count-#{key}"
  CACHE_USER_FOLLOWER_IDS = "user-follower-ids-#{key}"
  CACHE_USER_RECOMMENDATION_IDS = "user-recommendation-ids-#{key}"
  CACHE_USER_FOLLOWEE_IDS = "user-followee-ids-#{key}"
  CACHE_COLLECTION_CATEGORIES = "all-categories-#{key}"
  CACHE_TOP_COLLECTIONS = "all-categories-#{key}"
  CACHE_SCHOOL_COLLECTIONS_ID = "school-collections-#{key}"
  CACHE_ALL_COLLECTIONS_ID = "all-collections-#{key}"
  CACHE_COLLECTIONS_FOR_USER = "user-collections-#{key}"
  CACHE_USER_CREATED_COLLECTIONS = "user-created-collections-#{key}"
  CACHE_USER_FOLLOW_COLLECTIONS = "user-following-collections-#{key}"
  CACHE_FEED_ITEM_USER_STORIES = "feed-items-user-stories-#{key}"
  CACHE_SHOULD_SEND_FOLLOWER = "user-follower-email-#{key}"
  CACHE_SHOULD_SEND_KUDOS = "user-kudos-email-#{key}"
  CACHE_SHOULD_SEND_QUESTION = "user-ask-question-email-#{key}"
end